python plot_bird.py 0
python plot_bird.py 1
python plot_bird.py 2
python plot_bird.py 3
python plot_bird.py 4
python plot_bird.py 5
python plot_bird.py 6
python plot_bird.py 7
python plot_bird.py 8
python plot_bird.py 9
python plot_bird.py 10
python plot_bird.py 11
python plot_bird.py 12
python plot_bird.py 13
python plot_bird.py 14
python plot_bird.py 15
python plot_bird.py 16
python plot_bird.py 17
python plot_bird.py 18
python plot_bird.py 19
python plot_bird.py 20
